name: Build Plugin ZIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build MO files
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar i18n make-mo languages
          rm wp-cli.phar
      - name: Upload theme
        uses: actions/upload-artifact@v4
        with:
          name: rotaract-family
          path: |
            /home/runner/work/rotaract-family
            !/home/runner/work/rotaract-family/rotaract-family/.*
            !/home/runner/work/rotaract-family/rotaract-family/devenv*
